### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by FlawTECH** [vug/freqazoid#16]
Hi,
I'd really like to reuse some parts of your code in a project of mine.
However, without a license, I am unable to do so without legal risk (even if extremely unlikely).

Would you mind adding one to your project please ?

Here is a link explaining how to do it: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

I suggest the MIT License since it's one of the best out there for free (as in freedom) and open source code.

Thanks !

**Comment by vug** [comment]
Hi @FlawTECH ! Added MIT license to the project per your suggestion. Let me know if freqazoid code has any use for you. Have a good way!

**Comment by FlawTECH** [comment]
Thank you so much ! I was really looking forward to reuse / adapt some of your algorithms such as the fundamental frequency calculation in a project I'm working on and your example is exactly what I'm looking for; I'm lucky you're still active on here.

Have a good way as well !
